version: '3.8'
services:
  mysql-db:
    image: mysql:8.0
    container_name: matchhub_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: matchhub_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis-cache:
    image: redis:alpine
    container_name: matchhub_redis
    ports:
      - "6379:6379"

volumes:
  mysql_data: