spring:
  application:
    name: matchhub-backend

  # Cấu hình kết nối MySQL (Matchhub DB)
  datasource:
    url: jdbc:mysql://localhost:3306/matchhub_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình Hibernate (ORM)
  jpa:
    hibernate:
      ddl-auto: update  # Tự động tạo/cập nhật bảng dựa trên Class Entity
    show-sql: true      # In câu lệnh SQL ra console để dễ debug
    properties:
      hibernate:
        format_sql: true # Format code SQL cho dễ nhìn

  # Cấu hình Redis Cache
  data:
    redis:
      host: localhost
      port: 6379