spring:
  application:
    name: matchhub

  # Cấu hình MySQL
  datasource:
    url: jdbc:mysql://localhost:3306/matchhub_db?useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Cấu hình Hibernate (Tự động sinh bảng dựa trên Code)
  jpa:
    hibernate:
      ddl-auto: update # Tự động update schema khi code Entity thay đổi
    show-sql: true # Hiển thị câu lệnh SQL ra console để debug
    properties:
      hibernate:
        format_sql: true

  # Cấu hình Redis
  data:
    redis:
      host: localhost
      port: 6379